# Generated by Django 4.1.1 on 2022-10-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEspecialidad', models.CharField(max_length=45, verbose_name='Nombre Especialidad')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoGenero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NODEFINIDO', 'No Definido')], default='NODEFINIDO', max_length=10, verbose_name='Tipo De Genero')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaDisponible', models.CharField(max_length=45, verbose_name='Hora Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNacionalidad', models.TextField(max_length=45, verbose_name='Nombre de Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=45, verbose_name='apellidos')),
                ('tipoDocumento', models.CharField(choices=[('C.C', 'Cedula de Ciudadania'), ('T.I', 'Tarjeta de Identidad'), ('C.E', 'Cedula de Extranjeria'), ('P.P', 'Pasaporte')], default='C.C', max_length=10, verbose_name='Tipo de Documento')),
                ('numDocumento', models.CharField(max_length=50, verbose_name='Numero de Documento')),
                ('rh', models.CharField(max_length=45, verbose_name='Tipo de Sangre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=45, verbose_name='Correo Electronico')),
                ('fechaNacimiento', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Nacimiento')),
                ('nombreContacto', models.CharField(max_length=45, verbose_name='Nombre Contacto Familiar')),
                ('telefonoContacto', models.CharField(max_length=20, verbose_name='Telefono Contacto Familiar')),
                ('clave', models.CharField(max_length=45, verbose_name='Clave de seguridad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEcografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoEcografia', models.CharField(max_length=45, verbose_name='Nombre Tipo de Ecografia')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('preparacionEcografia', models.CharField(max_length=45, verbose_name='Preparacion Ecografia')),
                ('estado', models.CharField(max_length=45, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLaboratorio', models.CharField(max_length=45, verbose_name='Nombre de Laboratorio')),
                ('preparacionLaboratorio', models.CharField(max_length=45, verbose_name='Preparacion Laboratorio')),
                ('estado', models.BooleanField(choices=[('True', 'Activo'), ('False', 'Inactivo')], default='True', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.especialidad', verbose_name='Tipo de Ecografia')),
                ('medicinaGeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.medicinageneral', verbose_name='Medicina General')),
                ('tipoEcografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.tipoecografia', verbose_name='Tipo de Ecografia')),
                ('tipoLaboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.tipolaboratorio', verbose_name='Tipo de Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('C.C', 'Cedula de Ciudadania'), ('P.P', 'Pasaporte'), ('C.E', 'Cedula de Extranjeria')], default='C.C', max_length=10, verbose_name='Tipo de Documento')),
                ('numDocumento', models.CharField(max_length=45, verbose_name='Numero de Documento')),
                ('nombres', models.TextField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.TextField(max_length=45, verbose_name='apellidos')),
                ('email', models.CharField(max_length=45, verbose_name='Correo Electronico')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.especialidad', verbose_name='Especialidad')),
                ('horarioDisponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.horariodisponible', verbose_name='Horario Disponible')),
            ],
        ),
        migrations.AddField(
            model_name='medicinageneral',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.medico', verbose_name='Medico'),
        ),
    ]
