# Generated by Django 4.1.1 on 2022-11-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='clave',
        ),
    ]
