# Generated by Django 4.1.1 on 2022-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_tipolaboratorio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=45, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=45, verbose_name='nombres'),
        ),
    ]
