# Generated by Django 4.1.1 on 2022-11-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_paciente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(max_length=45, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numDocumento',
            field=models.CharField(max_length=50, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefonoContacto',
            field=models.CharField(max_length=20, verbose_name='Teléfono Contacto Familiar'),
        ),
    ]
