# Generated by Django 4.1.1 on 2022-10-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_paciente_genero_remove_paciente_nacionalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='estado',
        ),
    ]
