# Generated by Django 4.1.1 on 2022-10-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_remove_paciente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='servicio',
        ),
    ]
