# Generated by Django 4.1.1 on 2022-10-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_remove_paciente_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.BooleanField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado'),
        ),
    ]
