# Generated by Django 4.1.1 on 2022-10-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado'),
        ),
    ]
