# Generated by Django 4.1.1 on 2022-10-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombres de tipo de servicios')),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripcion de los servicios')),
                ('estado', models.BooleanField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaCita', models.DateTimeField(help_text='00:00', verbose_name='Hora de la Cita')),
                ('fechaCita', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de la Cita')),
                ('costo', models.CharField(max_length=45, verbose_name='Precio de la Cita')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.servicio', verbose_name='Servicio')),
            ],
        ),
    ]
