# Generated by Django 4.1.1 on 2022-11-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HoraDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=45, verbose_name='Hora Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombres de tipo de servicios')),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripcion de los servicios')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='FechaDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fechas Disponibles')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.servicio', verbose_name='Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.agenda', verbose_name='Fechas Disponibles')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.fechadisponible', verbose_name='Fechas Disponibles'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horaDisponible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.horadisponible', verbose_name='Hora Disponible'),
        ),
    ]
