# Generated by Django 4.1.1 on 2022-11-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_alter_horadisponible_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
