# Generated by Django 4.1.1 on 2022-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_remove_cita_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaCita',
            field=models.DateField(verbose_name='Fecha de la Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horaCita',
            field=models.TimeField(verbose_name='Hora de la Cita'),
        ),
    ]
