# Generated by Django 4.1.1 on 2022-11-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_agenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.CharField(default=2, max_length=45, verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
