# Generated by Django 4.1.1 on 2022-11-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_alter_cita_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.agenda', verbose_name='Servicio y Fechas Disponibles'),
        ),
    ]
