# Generated by Django 4.1.1 on 2022-10-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaCita', models.DateTimeField(help_text='00:00', verbose_name='Hora de la Cita')),
                ('fechaCita', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de la Cita')),
                ('costo', models.CharField(max_length=45, verbose_name='Precio de la Cita')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEspecialidad', models.CharField(max_length=45, verbose_name='Nombre Especialidad')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.TextField(max_length=45, verbose_name='apellidos')),
                ('tipoDocumento', models.CharField(default=('C.C', 'Cedula de Ciudadania'), max_length=10, verbose_name='Tipo de Documento')),
                ('numDocumento', models.CharField(max_length=50, verbose_name='Numero de Documento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=45, verbose_name='Correo Electronico')),
                ('clave', models.CharField(max_length=45, verbose_name='Clave de seguridad')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='horarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaDisponible', models.CharField(max_length=45, verbose_name='Hora Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='medicinaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNacionalidad', models.TextField(max_length=45, verbose_name='Nombre de Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tipoEcografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoEcografia', models.CharField(max_length=45, verbose_name='Nombre Tipo de Ecografia')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('preparacionEcografia', models.CharField(max_length=45, verbose_name='Preparacion Ecografia')),
                ('estado', models.CharField(max_length=45, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='tipoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tipoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLaboratorio', models.CharField(max_length=45, verbose_name='Nombre de Laboratorio')),
                ('preparacionLaboratorio', models.CharField(max_length=45, verbose_name='Preparacion Laboratorio')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.especialidad', verbose_name='Tipo de Ecografia')),
                ('medicinaGeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.medicinageneral', verbose_name='Medicina General')),
                ('tipoEcografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.tipoecografia', verbose_name='Tipo de Ecografia')),
                ('tipoLaboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.tipolaboratorio', verbose_name='Tipo de Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.TextField(max_length=45, verbose_name='apellidos')),
                ('tipoDocumento', models.CharField(default=('C.C', 'Cedula de Ciudadania'), max_length=10, verbose_name='Tipo de Documento')),
                ('numDocumento', models.CharField(max_length=50, verbose_name='Numero de Documento')),
                ('rh', models.CharField(max_length=45, verbose_name='Tipo de Sangre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=45, verbose_name='Correo Electronico')),
                ('fechaNacimiento', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Nacimiento')),
                ('nombreContacto', models.CharField(max_length=45, verbose_name='Nombre Contacto Familiar')),
                ('telefonoContacto', models.CharField(max_length=20, verbose_name='Telefono Contacto Familiar')),
                ('clave', models.CharField(max_length=45, verbose_name='Clave de seguridad')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.genero', verbose_name='Genero')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.nacionalidad', verbose_name='Nacionalidad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.servicio', verbose_name='Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(default=('C.C', 'Cedula de Ciudadania'), max_length=10, verbose_name='Tipo de Documento')),
                ('numDocumento', models.CharField(max_length=45, verbose_name='Numero de Documento')),
                ('nombres', models.TextField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.TextField(max_length=45, verbose_name='apellidos')),
                ('email', models.CharField(max_length=45, verbose_name='Correo Electronico')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.especialidad', verbose_name='Especialidad')),
                ('horarioDisponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.horariodisponible', verbose_name='Horario Disponible')),
            ],
        ),
        migrations.AddField(
            model_name='medicinageneral',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.medico', verbose_name='Medico'),
        ),
        migrations.CreateModel(
            name='historialDeCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.cita', verbose_name='Cita')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.servicio', verbose_name='Servicio'),
        ),
    ]
