# Generated by Django 4.1.1 on 2022-10-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='estado',
        ),
        migrations.RemoveField(
            model_name='historialdecitas',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='medicinageneral',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='horarioDisponible',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='medicinaGeneral',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipoEcografia',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipoLaboratorio',
        ),
        migrations.DeleteModel(
            name='tipoDocumento',
        ),
        migrations.DeleteModel(
            name='tipoGenero',
        ),
        migrations.DeleteModel(
            name='cita',
        ),
        migrations.DeleteModel(
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='genero',
        ),
        migrations.DeleteModel(
            name='historialDeCitas',
        ),
        migrations.DeleteModel(
            name='horarioDisponible',
        ),
        migrations.DeleteModel(
            name='medicinaGeneral',
        ),
        migrations.DeleteModel(
            name='medico',
        ),
        migrations.DeleteModel(
            name='nacionalidad',
        ),
        migrations.DeleteModel(
            name='paciente',
        ),
        migrations.DeleteModel(
            name='servicio',
        ),
        migrations.DeleteModel(
            name='tipoEcografia',
        ),
        migrations.DeleteModel(
            name='tipoLaboratorio',
        ),
    ]
