# Generated by Django 4.1.1 on 2022-10-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEspecialidad', models.CharField(max_length=45, verbose_name='Nombre Especialidad')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='horarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaDisponible', models.CharField(max_length=45, verbose_name='Hora Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='medicinaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tipoEcografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoEcografia', models.CharField(max_length=45, verbose_name='Nombre Tipo de Ecografia')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('preparacionEcografia', models.CharField(max_length=45, verbose_name='Preparacion Ecografia')),
                ('estado', models.CharField(max_length=45, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='tipoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLaboratorio', models.CharField(max_length=45, verbose_name='Nombre de Laboratorio')),
                ('preparacionLaboratorio', models.CharField(max_length=45, verbose_name='Preparacion Laboratorio')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.especialidad', verbose_name='Tipo de Ecografia')),
                ('medicinaGeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.medicinageneral', verbose_name='Medicina General')),
                ('tipoEcografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipoecografia', verbose_name='Tipo de Ecografia')),
                ('tipoLaboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipolaboratorio', verbose_name='Tipo de Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(default=('C.C', 'Cedula de Ciudadania'), max_length=10, verbose_name='Tipo de Documento')),
                ('numDocumento', models.CharField(max_length=45, verbose_name='Numero de Documento')),
                ('nombres', models.TextField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.TextField(max_length=45, verbose_name='apellidos')),
                ('email', models.CharField(max_length=45, verbose_name='Correo Electronico')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('estado', models.BooleanField(max_length=10, verbose_name='Estado')),
                ('horarioDisponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.horariodisponible', verbose_name='Horario Disponible')),
            ],
        ),
        migrations.AddField(
            model_name='medicinageneral',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.medico', verbose_name='Medico'),
        ),
    ]
